on:
  push:
    branches: [ release ]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set env variables
      uses: ./github/env/
    - run: sudo apt-get install binutils-aarch64-linux-gnu
    - run: sudo apt-get install device-tree-compiler
    - run: sudo apt-get install g++-aarch64-linux-gnu
    - run: sudo apt-get install gcc-aarch64-linux-gnu
    - run: sudo apt-get install autopoint
    - run: sudo apt-get install lzop
    - run: sudo apt-get install libipc-run-perl
    - run: make -j3 build/pearl.macho{release}
    - run: make -j3 build/debootstrap.macho{release}
    - run: make -j3 build/m1n1.macho{release}
    - run: make -j3 {release}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
