on:
  push:
    branches: [ release ]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./g/github/env/
    - run: sudo apt-get update
    - run: sudo apt-get install autopoint
    - run: sudo apt-get install lzop
    - run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
    - run: sudo apt-get install libipc-run-perl
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support
    - run: sudo apt-get install gettext
    - run: sudo apt-get install xz-utils
    - run: sudo apt-get install device-tree-compiler
    - run: sudo apt-get install libtool-bin
    - run: make -j13 build/binutils-gdb/done/install
    - run: make -j13 build/linux/done/headers/install
    - run: make -j13 build/glibc/done/headers/install
    - run: make -j13 build/gcc/done/gcc/install
    - run: make -j13 build/toolchain.tar
    - run: make -j13 build/glibc/done/glibc/install
    - run: make -j13 build/gcc/done/libgcc/install
    - run: make -j13 build/ncurses/done/install
    - run: make -j13 build/dialog/done/install
    - run: make -j13 build/screen/done/install
    - run: make -j13 build/procps/done/install
    - run: make -j13 build/busybox/done/install
    - run: make -j13 build/kexec-tools/done/install
    - run: make -j13 build/emacs/done/cross/install
    - run: make -j13 build/perl/done/install
    - run: make -j13 build/IPC-Run/done/install
    - run: make -j13 build/slurp/done/install
    - run: make -j13 build/libnl/done/install
    - run: make -j13 build/memtool/done/install
    - run: make -j13 build/libuuid/done/install
    - run: make -j13 build/json-c/done/install
    - run: make -j13 build/popt/done/install
    - run: make -j13 build/libblkid/done/install
    - run: make -j13 build/libaio/done/install
    - run: make -j13 build/lvm2/done/install
    - run: make -j13 build/openssl/done/install
    - run: make -j13 build/cryptsetup/done/install
    - run: make -j13 build/nvme-cli/done/install
    - run: make -j13 build/dtc/done/install
    - run: make -j13 build/wpa_supplicant/done/install
    - run: make -j13 build/userspace/done/install
    - run: make -j13 build/barebox/done/install
    - run: make -j13 build/m1n1/done/install
    - run: make -j13 build/grub/done/install
    - run: make -j13 build/u-boot/done/install
    - run: make -j13 build/userspace.tar
    - run: make -j13 build/linux/pearl.image
    - run: make -j13 build/linux/pearl.image.macho
    - run: cp build/linux/pearl.image.macho build/pearl.macho
    - run: make -j3 build/pearl.macho{release}
    - run: make -j3 {release}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
